import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import Navbar from '@/components/Navbar'
import Providers from '@/components/Providers'
import "react-loading-skeleton/dist/skeleton.css"
import { Toaster } from '@/components/ui/toaster'
import 'simplebar-react/dist/simplebar.min.css'
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'The Library',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
        <Providers>
          <body className={cn('min-h-screen font-sans antialiased grainy', inter.className)}>
            <ThemeProvider attribute="class" defaultTheme='light'>
            <Toaster/>
            <Navbar/>
              {children}
            </ThemeProvider>
          </body>
        </Providers>
    </html>
  )
}
